            if confidence_pct < 70:
                st.warning("⚠️ Low confidence detection. Please make sure that the photo was clicked with the leaf on a WHITE background. Otherwise, please consult an agricultural expert.")
            
            report = f"""
AGRIVISION DISEASE DIAGNOSIS REPORT
====================================

Disease: {treatment_info['disease_name']}
Confidence: {confidence_pct:.1f}%

Description:
{treatment_info['description']}

ORGANIC TREATMENT:
{chr(10).join([f"{i+1}. {t}" for i, t in enumerate(treatment_info['organic_treatment'])])}

CHEMICAL TREATMENT:
{chr(10).join([f"{i+1}. {t}" for i, t in enumerate(treatment_info['chemical_treatment'])])}

PREVENTION:
{chr(10).join([f"{i+1}. {p}" for i, p in enumerate(treatment_info['prevention'])])}

---
Generated by AgriVision - AI Plant Disease Detection
"""
                st.download_button(
                    label="Download Text Report",
                    data=report,
                    file_name="agrivision_report.txt",
                    mime="text/plain"
                )